name: offdabreak
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/PaintballMan.png
    - assets/TransparentMan.png
    - assets/LoneStar_Logo.png
    - assets/WorldCup_Logo.png
    - assets/midwest.png
    - assets/TampaBay.png
    - assets/AtlanticCity.png

